export const TOKEN_LOGIN = 'token'
export const NAME_LOGIN='name'
export const PASSWORD_LOGIN='password'
export const USER_INFO='userInfo'
export const MENU_INFO='menuInfo'
export const ROLE_LIST='role/list'
export const DEPARTMENT_LIST='department/list'
